### ISSUE TITLE
Downloaded binaries don't have execution permission

### ISSUE THREAD

**Issue by mmarchini** [mrkmarron/node-chakracore-time-travel-debugger#2]
On Mac OS X with VS Code 1.22.2 the binaries have rw permissions only, thus VS Code throws an EACCESS error.

<img width="1316" alt="screen shot 2018-04-19 at 12 56 37 pm" src="https://user-images.githubusercontent.com/4048656/39003391-2528b936-43d1-11e8-83a3-37fcb86bb84d.png">

<img width="1316" alt="screen shot 2018-04-19 at 12 56 41 pm" src="https://user-images.githubusercontent.com/4048656/39003392-254953a8-43d1-11e8-880f-02b5ff758e49.png">

**Comment by mrkmarron** [comment]
Fixed in latest version (1.5). 

vsce on Windows does not respect posix permissions -- so I need to remember to publish from my Mac.
