### ISSUE TITLE
Setting a default port

### ISSUE THREAD

**Issue by aaronnuu** [mrkmarron/node-chakracore-time-travel-debugger#4]
I'd like to set my application to run with the debugging config from my package.json but I'm not sure how to set up a consistent port for the debugger to attach to.

I tried setting the port in my launch.json config but the debugger then didn't add any args past --tt-debug

**Comment by mrkmarron** [comment]
Hi @AaronW9090, thanks for the report. I was able to reproduce the issue and prototype a fix. I am at JSConfEU for the next couple of days but will plan to fix and update when I get back next week.

**Comment by mrkmarron** [comment]
This is fixed in the latest version (0.2.2) of the extension.

**Comment by aaronnuu** [comment]
Awesome, thanks Mark.
