### ISSUE TITLE
Failing to launch debug session

### ISSUE THREAD

**Issue by eburgwedel** [mrkmarron/node-chakracore-time-travel-debugger#5]
Upon launching a debug session, I can use breakpoints and step **forward** with no problem. Trying to step **back**, however, I get the following error message: 

"TTD: Failed to launch time-travel debugging session -- "Could not write TTD trace -- has synchronous module loading completed?"

I this is independent of the code I'm trying to debug, it's any three lines of vanilla Javascript.

My config is very straight forward:
```
launch.json
        {
            "name": "Time-Travel Live",
            "type": "node-chakracore-time-travel-debugger",
            "request": "launch",
            "program": "${workspaceFolder}/${relativeFile}",
            "cwd": "${workspaceFolder}"
        },
```

```
ts-node v7.0.1
node v11.3.0
typescript v3.2.1

```
There is a similar problem reported here: https://stackoverflow.com/questions/53496629/could-not-write-ttd-trace-has-synchronous-module-loading-completed-nodejs-de

**Comment by mrkmarron** [comment]
Hi @eburgwedel, thanks for opening the issue and flagging the stackoverflow question. 

The Node.js loading process is a bit complicated and, as a result, the TTD process does not record the execution of the synchronous module loading activity (basically anything before the event loop starts to dispatch) so the time-travel debugger cannot replay this part of the application. 

I took the code from the stackoverflow post and just wrapped it in a `setImmediate` so it executes after the synchronous loads:
```
setImmediate(() => {
    console.log("hi");
    var array = [1, 2, 3]
    for (let index = 0; index < array.length; index++) {
        console.log(array[index]);
    }
});
```
Now setting a breakpoint at the array assignment etc. and stepping back should work fine. 

Thanks and let me know if you are still seeing a problem.

**Comment by eburgwedel** [comment]
Sweet little trap, learned something. Thanks, Mark!
